set $term alacritty --config-file /etc/alacritty/alacritty.toml
set $menu wofi --conf=/etc/wofi/config --style=/etc/wofi/style.css
set $webBrowser firefox
# Start a terminal
bindsym $mod+q exec $term

# Open Firefox
bindsym $mod+m exec firefox

# Open chatGPT
bindsym $mod+c exec firefox chatgpt.com

# Open neovim
bindsym $mod+n exec alacritty -e nvim

# Open YouTube
bindsym $mod+y exec firefox youtube.com
#
# Start your launcher
bindsym $mod+d exec $menu
