set $mod Mod4
set $left h
set $down j
set $up k
set $right l
bindsym --to-code {
    $mod+b splith
    $mod+v splitv
}


# Kill focused window
bindsym $mod+Shift+q kill

# Reload the configuration file
bindsym $mod+Shift+c reload

# Exit sway (logs you out of your Wayland session)
bindsym $mod+Shift+e exec swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -b 'Yes, exit sway' 'swaymsg exit'
bindsym $mod+r mode "resize"
include ~/.config/sway/config.d/bindings/windowBindings.conf
include ~/.config/sway/config.d/bindings/applicationBindings.conf
include ~/.config/sway/config.d/bindings/workspaceBindings.conf
include ~/.config/sway/config.d/bindings/keyBindings.conf
include ~/.config/sway/config.d/bindings/screenshotBindings.conf
include ~/.config/sway/config.d/bindings/mediaBindings.conf
